<form class="form-login p-2" id="form-login" action='/login' method="POST">
    <h2 class="text-light">Bejelentkezés</h2>
    <div class="form-group mt-3 mb-2">
        <input type="user" class="form-control" name="user" aria-describedby="user"placeholder="Felhasználónév">
    </div>
    <div class="form-group mt-4">
        <input type="password" class="form-control" name="psw" placeholder="Jelszó">
    </div>
    <button type="submit" class="btn btn-success my-3" id="login" name="login">Bejelentkezés</button>
    <p class="text-light">Ha nincs még felhasználó fiókod <a href="/register">katt ide!!!</a>
</form>