<?php

$isValidClass = function ($key) use ($params) {
  if (!$params['errorMessages']) {
    return "";
  }
  return count($params['errorMessages'][$key] ?? []) ? "is-invalid" : "is-valid";
};
?>

<div class="card mt-2 p-2">
        <div class="card-header text-center ">
           <h3 class="text-white">
           <strong>Kiszállítási cím hozzáadása:</strong>
           </h3>   
        </div>
        <form id='back' action='/order' method="GET">
        </form> 
        <div class="card-body">
            <form class="form-login p-2"  action='/add-new-address' method="POST">
            <div class="form-group mt-3 mb-2">
                <label for="inputAddress">Cím:</label>
                <input type="text" name="address" value="<?= $params['values']['address'] ?? '' ?>" class="form-control <?= $isValidClass('address') ?>" placeholder="pl: Darabos utca 10">
            <div class="invalid-feedback">
            <?php foreach ($params['errorMessages']['address'] as $error) : ?>
              <?= $error ?> <br />
            <?php endforeach; ?>
            </div>
            </div>
            <div class="form-group mt-4">
                <label for="inputInfo">Egyébb info:</label>
                <input type="text" name="info" value="<?= $params['values']['info'] ?? '' ?>" class="form-control <?= $isValidClass('info')?>" placeholder="pl: 1 em. 4. aj.">
            </div>
            <button type="submit" form='back' class="btn btn-dark my-3">Vissza</button>
            <button type="submit" class="btn btn-success my-3">Mentés</button>     
          </div>
</div>