<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="public/css/style.css" rel="stylesheet">
    <title>PizzaMania</title>
</head>
<body>
    <div class="container">
        <div class="container bg-danger mb-3 p-2" id="menu">
            <button class="btn btn-danger" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling"><img src="public/img/Menu-icon.png" alt=""></button>
            <div class="offcanvas offcanvas-start" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
                <div class="offcanvas-header bg-danger">
                    <h5 class="offcanvas-title" id="offcanvasScrollingLabel">Menü</h5>
                    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <div class="container mt-3">
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link" href="/">Étlap</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/about-us">Rólunk</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/register">Regisztráció</a> 
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <a href="/">
                <img class="float-end" src="public/img/Pizza-slice.png" alt="">
                <h5 class="float-end mt-2 me-2 text-white"> PizzaMánia</h5>
            </a>
        </div>
        <div class="row">
            <div class="col-lg-8">
                <?=$params['content']?>
            </div>
            <div class="col-sm">
                    <?=$params['profil']?>
                <div class="col">
                    <?=$params['cart']?>                  
                </div>
            </div>
        </div>                
        <div class= "container mt-3 p-2 bg-danger text-white text-center">
            <p>
            PizzaMánia, mániánk a finom és ízletes pizzák készítése :)
            </p>
        </div>    
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>    
</body>
</html>